// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef TARDIS_ODB_HXX
#define TARDIS_ODB_HXX

// Begin prologue.
//
#include <odb/qt/version.hxx>
#if ODB_QT_VERSION != 2040000 // 2.4.0
#  error ODB and C++ compilers see different libodb-qt interface versions
#endif
#include <odb/qt/basic/mysql/qstring-traits.hxx>
#include <odb/qt/basic/mysql/qbyte-array-traits.hxx>
#include <odb/qt/basic/mysql/quuid-traits.hxx>
#include <odb/qt/containers/qhash-traits.hxx>
#include <odb/qt/containers/qlist-traits.hxx>
#include <odb/qt/containers/qlinked-list-traits.hxx>
#include <odb/qt/containers/qmap-traits.hxx>
#include <odb/qt/containers/qset-traits.hxx>
#include <odb/qt/containers/qvector-traits.hxx>
#include <odb/qt/date-time/mysql/qdate-traits.hxx>
#include <odb/qt/date-time/mysql/qtime-traits.hxx>
#include <odb/qt/date-time/mysql/qdate-time-traits.hxx>
#include <QtCore/QSharedPointer>
#include <odb/qt/smart-ptr/pointer-traits.hxx>
#include <odb/qt/smart-ptr/wrapper-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "tardis.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // tardis
  //
  template <>
  struct class_traits< ::tardis >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::tardis >
  {
    public:
    typedef ::tardis object_type;
    typedef ::QSharedPointer< ::tardis > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // tardis
  //
  template <typename A>
  struct pointer_query_columns< ::tardis, id_mysql, A >
  {
    // tardis_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        unsigned int,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    tardis_id_type_;

    static const tardis_id_type_ tardis_id;

    // track_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        unsigned int,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    track_id_type_;

    static const track_id_type_ track_id;

    // tardis_longitude
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        double,
        mysql::id_double >::query_type,
      mysql::id_double >
    tardis_longitude_type_;

    static const tardis_longitude_type_ tardis_longitude;

    // tardis_latitude
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        double,
        mysql::id_double >::query_type,
      mysql::id_double >
    tardis_latitude_type_;

    static const tardis_latitude_type_ tardis_latitude;

    // tardis_date
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::QDateTime,
        mysql::id_datetime >::query_type,
      mysql::id_datetime >
    tardis_date_type_;

    static const tardis_date_type_ tardis_date;
  };

  template <typename A>
  const typename pointer_query_columns< ::tardis, id_mysql, A >::tardis_id_type_
  pointer_query_columns< ::tardis, id_mysql, A >::
  tardis_id (A::table_name, "`tardis_id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::tardis, id_mysql, A >::track_id_type_
  pointer_query_columns< ::tardis, id_mysql, A >::
  track_id (A::table_name, "`track_id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::tardis, id_mysql, A >::tardis_longitude_type_
  pointer_query_columns< ::tardis, id_mysql, A >::
  tardis_longitude (A::table_name, "`tardis_longitude`", 0);

  template <typename A>
  const typename pointer_query_columns< ::tardis, id_mysql, A >::tardis_latitude_type_
  pointer_query_columns< ::tardis, id_mysql, A >::
  tardis_latitude (A::table_name, "`tardis_latitude`", 0);

  template <typename A>
  const typename pointer_query_columns< ::tardis, id_mysql, A >::tardis_date_type_
  pointer_query_columns< ::tardis, id_mysql, A >::
  tardis_date (A::table_name, "`tardis_date`", 0);

  template <>
  class access::object_traits_impl< ::tardis, id_mysql >:
    public access::object_traits< ::tardis >
  {
    public:
    struct id_image_type
    {
      unsigned int id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // tardis_id
      //
      unsigned int tardis_id_value;
      my_bool tardis_id_null;

      // track_id
      //
      unsigned int track_id_value;
      my_bool track_id_null;

      // tardis_longitude
      //
      double tardis_longitude_value;
      my_bool tardis_longitude_null;

      // tardis_latitude
      //
      double tardis_latitude_value;
      my_bool tardis_latitude_null;

      // tardis_date
      //
      MYSQL_TIME tardis_date_value;
      my_bool tardis_date_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct track_id_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 5UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::tardis, id_common >:
    public access::object_traits_impl< ::tardis, id_mysql >
  {
  };

  // tardis
  //
  template <>
  struct alias_traits<
    ::track,
    id_mysql,
    access::object_traits_impl< ::tardis, id_mysql >::track_id_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::tardis, id_mysql >
  {
    // track_id
    //
    typedef
    odb::alias_traits<
      ::track,
      id_mysql,
      access::object_traits_impl< ::tardis, id_mysql >::track_id_tag>
    track_id_alias_;
  };

  template <typename A>
  struct query_columns< ::tardis, id_mysql, A >:
    query_columns_base< ::tardis, id_mysql >
  {
    // tardis_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        unsigned int,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    tardis_id_type_;

    static const tardis_id_type_ tardis_id;

    // track_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        unsigned int,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    track_id_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::track,
        id_mysql,
        track_id_alias_ > >
    track_id_pointer_type_;

    struct track_id_type_: track_id_pointer_type_, track_id_column_type_
    {
      track_id_type_ (const char* t, const char* c, const char* conv)
        : track_id_column_type_ (t, c, conv)
      {
      }
    };

    static const track_id_type_ track_id;

    // tardis_longitude
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        double,
        mysql::id_double >::query_type,
      mysql::id_double >
    tardis_longitude_type_;

    static const tardis_longitude_type_ tardis_longitude;

    // tardis_latitude
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        double,
        mysql::id_double >::query_type,
      mysql::id_double >
    tardis_latitude_type_;

    static const tardis_latitude_type_ tardis_latitude;

    // tardis_date
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::QDateTime,
        mysql::id_datetime >::query_type,
      mysql::id_datetime >
    tardis_date_type_;

    static const tardis_date_type_ tardis_date;
  };

  template <typename A>
  const typename query_columns< ::tardis, id_mysql, A >::tardis_id_type_
  query_columns< ::tardis, id_mysql, A >::
  tardis_id (A::table_name, "`tardis_id`", 0);

  template <typename A>
  const typename query_columns< ::tardis, id_mysql, A >::track_id_type_
  query_columns< ::tardis, id_mysql, A >::
  track_id (A::table_name, "`track_id`", 0);

  template <typename A>
  const typename query_columns< ::tardis, id_mysql, A >::tardis_longitude_type_
  query_columns< ::tardis, id_mysql, A >::
  tardis_longitude (A::table_name, "`tardis_longitude`", 0);

  template <typename A>
  const typename query_columns< ::tardis, id_mysql, A >::tardis_latitude_type_
  query_columns< ::tardis, id_mysql, A >::
  tardis_latitude (A::table_name, "`tardis_latitude`", 0);

  template <typename A>
  const typename query_columns< ::tardis, id_mysql, A >::tardis_date_type_
  query_columns< ::tardis, id_mysql, A >::
  tardis_date (A::table_name, "`tardis_date`", 0);
}

#include "tardis-odb.ixx"

#include <odb/post.hxx>

#endif // TARDIS_ODB_HXX
