/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `event`;

CREATE TABLE `event` (
  `event_id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `event_name` TEXT NOT NULL,
  `submit_date` DATETIME NULL,
  `event_date` DATETIME NULL,
  `event_accepted` TINYINT(1) NOT NULL,
  `submitter_id` INT UNSIGNED NOT NULL)
 ENGINE=InnoDB;

/*
ALTER TABLE `event`
  ADD CONSTRAINT `event_submitter_id_fk`
    FOREIGN KEY (`submitter_id`)
    REFERENCES `user` (`user_id`)
*/

