/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `user_id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_name` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `first_name` TEXT NOT NULL,
  `last_name` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `type` ENUM('admin', 'moderator', 'simple_user', 'guest') NOT NULL,
  `registration_date` DATETIME NULL)
 ENGINE=InnoDB;

