/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `image`;

CREATE TABLE `image` (
  `image_id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `PATH` TEXT NOT NULL,
  `event_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `image_date` DATETIME NULL,
  `image_accepted` TINYINT(1) NOT NULL,
  `image_longitude` DOUBLE NOT NULL,
  `image_latitude` DOUBLE NOT NULL,
  `blob` LONGBLOB NULL)
 ENGINE=InnoDB;

/*
ALTER TABLE `image`
  ADD CONSTRAINT `image_event_id_fk`
    FOREIGN KEY (`event_id`)
    REFERENCES `odbevent` (`event_id`),
  ADD CONSTRAINT `image_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
*/

