/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `track`;

CREATE TABLE `track` (
  `track_id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `event_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL)
 ENGINE=InnoDB;

/*
ALTER TABLE `track`
  ADD CONSTRAINT `track_event_id_fk`
    FOREIGN KEY (`event_id`)
    REFERENCES `odbevent` (`event_id`),
  ADD CONSTRAINT `track_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
*/

